# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aedfbf3d2fdd07329659b9b21e5b305cd3b457eec1b7208fa2eca00c146ba06938ec303abe5e2c9555009f8751a796875b6ed6544756d497d85aec5727ea03e

test:
  secret_key_base: 5978b99e9b8c9ddac3607057cc06d2b8de1c4b0d5fde0ede1088bdf15d6d224a3d1e998e95b9e3429040314711e49c7d6d496f1e09d4cb9ac04e9923a9fde6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
